name: Upload coverage reports to Codecov
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}